-- Projects belong to a single workspace (N:1), with a short human-facing
-- "key" (e.g. ECOM, MOB, API) used as an identifier prefix within that
-- workspace. Same identifier strategy as V1: UUID primary key generated by
-- PostgreSQL via uuidv7().

CREATE TABLE projects (
    id           UUID         NOT NULL DEFAULT uuidv7(),
    name         VARCHAR(255) NOT NULL,
    key          VARCHAR(10)  NOT NULL,
    description  TEXT,
    workspace_id UUID         NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_workspace FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id),
    -- Project keys (ECOM, MOB, API...) only need to be unique within the
    -- workspace that owns them, not across the whole database.
    CONSTRAINT uq_projects_workspace_key UNIQUE (workspace_id, key)
);

-- No additional explicit index is needed here. The composite UNIQUE
-- (workspace_id, key) constraint above already creates a btree index with
-- workspace_id as its leading column, and btree indexes satisfy queries on
-- any leftmost prefix of their columns. That single index therefore serves
-- both the uniqueness check and plain "projects in workspace X" lookups
-- (unlike V1's users.workspace_id, which had no other index to piggyback
-- on). A separate single-column index on workspace_id would be redundant.
